from abc import ABC, abstractmethod
from typing import Dict


class Runner(ABC):
    """Runner Base Class for Process Execution

    The Runner base class describes the interface that must
    be implemented by an execution backend. Its task is to
    either dispatch a previously prepared [`Job`](eozilla_eoap.procolike.Job)
    to yet another external execution backend or execute it
    directly.

    Failures may be signaled by raising implementation-specific exceptions.
    """

    @abstractmethod
    def run(self, job_id: str, *args, **kwargs) -> Dict:
        """Submit a job to a processing backend.

        Args:
            job_id (str): Unique identifier for a job execution

        Returns:
            Dict: Results generated by the job execution.
        """
